hospital/hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('records/',include('records.urls')),
    path('',RedirectView.as_view(url='records/'))
]

hospital/records/urls.py
from django.urls import path
from . import views


app_name = 'records'
urlpatterns = [
    path('',views.home,name='home'),
    path('createpatient/', views.PatientCreate.as_view(),name='create_patient'),
    path('patient/<int:pk>/',views.PatientDetail.as_view(),name='patient_detail'),
    path('patients/',views.PatientList.as_view(),name='patient_view'),

    path('createrecords/',views.PatientRecordsCreate.as_view(),name='create_record'),
    path('record/<int:pk>',views.PatientRecordsDetail.as_view(),name='record_detail'),

]

hospital/records/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime

# Create your models here.



class PatientProfile(models.Model):
    BLOODTYPE_CHOICES = [
    ("A", "A"),
    ("AB", "AB"),
    ("B", "B"),
    ("O", "O"),
    ('-','None'),
]
    patient_name = models.CharField(max_length=100)
    patient_address = models.TextField(max_length=300)
    Patient_bloodtype = models.CharField(choices=BLOODTYPE_CHOICES,max_length=10)
    patient_age = models.IntegerField(default=0)
    patient_comorbid = models.TextField(default='No Comorbid')
    patient_note = models.TextField(default='None')
    patient_apply = models.DateTimeField(auto_created=True,auto_now=True)
    patient_systol = models.IntegerField(default=120)
    patient_diastol = models.IntegerField(default=80)

    class Meta:
        ordering = ['patient_name']
    def __str__(self) -> str:
        return f"{self.patient_name}"
    
    def get_absolute_url(self):
        return reverse("patient_detail", kwargs={"pk": self.pk})

class PatientRecords(models.Model):
    timestamp = models.DateTimeField(auto_created=True,auto_now=True)
    patient_name = models.ForeignKey(PatientProfile,on_delete=models.SET_NULL,blank=True,null=True)
    diagnose = models.TextField(max_length=300)
    prescription = models.ManyToManyField('MedCabinet')
    notes = models.TextField(max_length=300)
    follow_up = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['timestamp']

    def __str__(self) -> str:
        return f"Records {self.patient_name} on {self.timestamp}"
    
    def get_absolute_url(self):
        return reverse("records:record_detail", kwargs={"pk": self.pk})



class MedCabinet(models.Model):
    medicine_name = models.CharField(max_length=200)
    dose = models.TextField(max_length=10)
    description = models.TextField(max_length=300)
    stock = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.medicine_name} stock: {self.stock}"
    

hospital/records/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,CreateView,UpdateView,DeleteView,DetailView
from .models import PatientProfile,PatientRecords,MedCabinet
from django.db.models import F

# Create your views here.

def home(request):
    return render(request, 'records/home.html')

#PATIENT IDs
class PatientCreate(CreateView): #book_form.html
    model =  PatientProfile
    fields = '__all__'

class PatientDetail(DetailView):
    model = PatientProfile

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the patient records
        # context['patient_records'] = PatientRecords.objects.filter(patient_name=self.object)
        # for item in context['patient_records'].all():
        #     print(item.prescription)

        patient_records = PatientRecords.objects.filter(patient_name=self.object)
        for record in patient_records:
            record.prescriptions = record.prescription.all()
            #print(record.prescription)
        context['patient_records'] = patient_records
        print(context['patient_records'])
        return context

class PatientList(ListView):
    model=PatientProfile

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the patient records
        context['patients'] = PatientProfile.objects.all()
        return context

#PATIENT RECORDS 
class PatientRecordsCreate(CreateView): #patientrecords_form.html
    model =  PatientRecords
    fields = '__all__'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        response = super().form_valid(form)

        # Get the prescription from the form data
        prescriptions = form.cleaned_data.get('prescription')
        # Returning multiple querryset, each of them reffering to medicine instances:
        # <QuerySet [<MedCabinet: Paracetamol stock: 498>]>
        # <QuerySet [<MedCabinet: Thrombopop stock: 249>]>
        # <QuerySet [<MedCabinet: metaheuristik stock: 199>]>

        for prescription in prescriptions:
        # Decrease the stock of the prescribed medicine
            #print(MedCabinet.objects.filter(pk=prescription.pk))
            MedCabinet.objects.filter(pk=prescription.pk).update(stock=F('stock') - 1)  
            
            #for each queryset, it will matching the pk of the Medicine models with the querried from prescription 

        return response


class PatientRecordsDetail(DetailView):
    model = PatientRecords

#MEDICINE 

hospital/records/templates/records/home.html
{%extends 'base.html' %}

{% block content %}

<h1 style="text-align: center;"> THIS IS HOMEPAGE </h1>
{% endblock %}

hospital/records/templates/records/patientprofile_detail.html
{% extends 'base.html' %}

{% block content %}
<h1 style="text-align: center;" slot="align-items"></h1>
<div>
    <table style="align-items: center;align-self: flex-end;">
        <tr>
            <td>Name</td>
            <td> {{ patientprofile.patient_name }}</td>
        </tr>
        <tr>
            <td> Alamat </td>
            <td> {{ patientprofile.patient_address }}</td>
        </tr>
        <tr>
            <td> Golongan Darah </td>
            <td> {{ patientprofile.Patient_bloodtype }}</td>
        </tr>      
    </table>
    
</div>

<div>
    <h2>Medical Record History</h2>
    <hr>
    {% if patient_records %}
    <ul>
        {% for record in patient_records %}
        <h3>On {{ record.timestamp }}</h3>
        <p><b>Diagnose:</b> {{ record.diagnose }}</p>
        <p><b>Notes:</b> {{ record.notes }}</p>
        <p>Prescribed medicines:</p>
        <ul>
        {% for medicine in record.prescriptions %}
            <li>{{ medicine.medicine_name }}</li>
        {% endfor %}
        </ul>
        <hr>
    {% endfor %}
    </ul>
    {% else %}
    <p>There are no record to Show</p>
    {% endif %}
</div>


{% endblock %}

hospital/records/templates/records/patientprofile_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Create Patient Identity</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="CREATE">
</form>

{% endblock %}

hospital/records/templates/records/patientprofile_list.html
{% extends 'base.html' %}

{% block content %}
<h1 style="text-align: center;" slot="align-items">Patient List</h1>
{% for patient in patients %}

<a href="{% url 'records:patient_detail' pk=patient.pk %}">{{ patient.patient_name }}</a>
<br>


{% endfor %}


{% endblock %}

hospital/records/templates/records/patientrecords_detail.html
{% extends 'base.html' %}

{% block content %}
<h1 style="text-align: center;" slot="align-items"></h1>
<div>
    <table style="align-items: center;align-self: flex-end;">
        <tr>
            <td>timestamp</td>
            <td> {{ patientrecords.timestamp }}</td>
        </tr>
        <tr>
            <td> Nama </td>
            <td> {{ patientrecords.patient_name }}</td>
        </tr>
        <tr>
            <td> Diagnosis </td>
            <td> {{ patientrecords.diagnose }}</td>
        </tr>  
        
        <tr>
            <td> Prescription </td>
            <td> {{ patientrecords.prescription }}</td>
        </tr>  

        <tr>
            <td> Diagnosis </td>
            <td> {{ patientrecords.follow_up }}</td>
        </tr>  

        <tr>
            <td> Catatan Tambahan </td>
            <td> {{ patientrecords.notes }}</td>
        </tr>  
    </table>
    
</div>

{% endblock %}

hospital/records/templates/records/patientrecords_form.html
{% extends 'base.html' %}

{% block content %}
<div style="display: flex; justify-content: center; align-items: center; height: 20vh;">
<h1 style="text-align: center;">Create New Records</h1>
</div>
<div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="CREATE">
</form>
</div>

{% endblock %}

hospital/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hospital Data</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark" aria-label="First navbar example">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">RS Favorit Keluarga</a>
          <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
    
          <div class="navbar-collapse collapse" id="navbarsExample01" style="">
            <ul class="navbar-nav me-auto mb-2">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">View Patient</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href = "{% url 'records:patient_view' %}">List Patient</a>
              </li>

              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">View Medicine</a>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Create New</a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'records:create_patient' %}">Create New Patient</a></li>
                  <li><a class="dropdown-item" href="{% url 'records:create_record' %}">Create new Records</a></li>
                  <li><a class="dropdown-item" href="#">Create new Medicine</a></li>
                </ul>
              </li>
            </ul>
            <form role="search">
              <input class="form-control" type="search" placeholder="Search" aria-label="Search">
            </form>
          </div>
        </div>
      </nav>

    {% block content %}




    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>